@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTI1ZWE2Ni0zNzI1LTRiZWUtOTY5MC1hNjAzNzI0M2U3OGQiLCJpYXQiOjE3NzY1ODg5MjUsImV4cCI6MTc3NzE5MzcyNX0.ohRQIprywJNSGLOnrCZnKcrP2Ura3wqR2B03335fQSI

###Sign In ###
POST http://localhost:8000/auth/signin
Content-Type: application/json

{
 "email":"test1@gmail.com",
 "password":"test123"
}

###Sign In as admin ###
POST http://localhost:8000/auth/signin
Content-Type: application/json

{
 "email":"admin@gmail.com",
 "password":"test123"
}


### Create Profile ###
POST http://localhost:8000/profile
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "first_name":"Md Abdul",
    "last_name":"Rahim",
    "designation":"Professor",
    "country":"Bangladesh",
    "organization":"BUET",
    "user_type":"STUDENT"
}


### View all Profile ###
GET http://localhost:8000/profile
Authorization: Bearer {{token}}