@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4MDhlN2ZmZS04NTY5LTRkZmQtYTQwYS1mNDllOTc0NWMyNWYiLCJpYXQiOjE3NzU0NzMyOTcsImV4cCI6MTc3NjA3ODA5N30.HLDEnlJ9lB4EUZa6yWqwgkNwE020nPpfRnBbOQevges

###Sign In ###
POST http://localhost:8000/auth/signin
Content-Type: application/json

{
 "email":"test1@gmail.com",
 "password":"test123"
}

###Sign In as admin ###
POST http://localhost:8000/auth/signin
Content-Type: application/json

{
 "email":"admin@gmail.com",
 "password":"test123"
}


### Create Profile ###
POST http://localhost:8000/profile
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "first_name":"Md Abdul",
    "last_name":"Rahim",
    "designation":"Professor",
    "country":"Bangladesh",
    "organization":"BUET",
    "user_type":"STUDENT"
}


### View all Profile ###
GET http://localhost:8000/profile
Authorization: Bearer {{token}}