@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjE5MjRiNi0zZmFkLTQ3ZTgtOWM3OC1jMTBkYjk3NDM3MjciLCJpYXQiOjE3ODIxODg0NDksImV4cCI6MTc4Mjc5MzI0OX0.g3tnt38olKo98F6v7lAwNdcVPk6gHUMhZARP560MEaY

###Sign In admin ###
POST http://localhost:8000/auth/signin
Content-Type: application/json

{
 "email":"admin@gmail.com",
 "password":"test123"
}

### Seed data setting ###
GET http://localhost:8000/date-setting/seed
Authorization: Bearer {{token}}