@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YmQ0NTMzMy02Mzc0LTQ5M2QtYWE5Yi1lZWM5ZTg0OTcxYmUiLCJpYXQiOjE3ODA1NDgyODMsImV4cCI6MTc4MTE1MzA4M30.iNbMafwCOu1Bgl7mVXDAlEgHMfd56XynRlUiHUt_fhE


###Sign In admin ###
POST http://localhost:8000/auth/signin
Content-Type: application/json

{
 "email":"admin@gmail.com",
 "password":"test123"
}

### Seed data setting ###
GET http://localhost:8000/date-setting/seed
Authorization: Bearer {{token}}