@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmY2NlZDEyOS0wZGExLTRmNjQtYTM0YS0xOThmMmM0OTczYzAiLCJpYXQiOjE3NzU0NzM0NzUsImV4cCI6MTc3NjA3ODI3NX0.9zrTr8ESsFYFHhVnwLET8C1RilkEuRlezmQ-J0juGLM

###Sign In ###
POST http://localhost:8000/auth/signin
Content-Type: application/json

{
 "email":"test1@gmail.com",
 "password":"test123"
}

###Sign In as admin ###
POST http://localhost:8000/auth/signin
Content-Type: application/json

{
 "email":"admin@gmail.com",
 "password":"test123"
}

### Create Topic ###
POST http://localhost:8000/topic
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name":"typescript"
    
}

### View all Topic ###
GET http://localhost:8000/topic