@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YmQ0NTMzMy02Mzc0LTQ5M2QtYWE5Yi1lZWM5ZTg0OTcxYmUiLCJpYXQiOjE3ODAyOTIxNjQsImV4cCI6MTc4MDg5Njk2NH0.pSqAtIPDMc6sXdGU_I7mvFHysBnVazLVpPz-k-kreu0
@topicId_py=f23471c8-ec00-4574-afcd-c8c15102382b


@reviewer_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTI1ZWE2Ni0zNzI1LTRiZWUtOTY5MC1hNjAzNzI0M2U3OGQiLCJpYXQiOjE3NzcxNzQ0ODYsImV4cCI6MTc3Nzc3OTI4Nn0.8toj4K3LUQHvH6WGe0xxDqFUJT1yzYRVKEOQEPvKNrU

###Sign In ###
POST http://localhost:8000/auth/signin
Content-Type: application/json

{
 "email":"admin@gmail.com",
 "password":"test123"
}

###Sign In as reviewer ###
POST http://localhost:8000/auth/signin
Content-Type: application/json

{
 "email":"reviewer1@gmail.com",
 "password":"test123"
}


### Sign in as Author
POST http://localhost:8000/auth/signin
Content-Type: application/json

{
 "email":"test@gmail.com",
 "password":"test123"
}


### Create a abstract ###
POST http://localhost:8000/abstract
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title":"test abstract",
    "description":"this is a test abstract",
    "keyword":"test, abstract",
    "ip_address":"192.168.1.1",
    "topicId":"33a580a3-12e7-40cf-abb2-25d09c099374",
    "purpose":"this is the purpose of the abstract",
    "methodology":"this is the methodology of the abstract",
    "findings":"these are the findings of the abstract",
    "theoretical":"this is the theoretical implications of the abstract",
    "practical":"these are the practical implications of the abstract",
    "references":"these are the references of the abstract",
    "co_authors":[
        {
            "first_name":"co",
            "last_name":"author 1",
            "email":"co1@gmail.com",
            "organization":"test organization"
        },
        {
            "first_name":"co",
            "last_name":"author 2",
            "email":"co2@gmail.com",
            "organization":"test organization"
        }

    ]
}


#### Get all abstracts ###
GET http://localhost:8000/abstract
Authorization: Bearer {{token}}


### Get user's abstracts ###
GET http://localhost:8000/abstract/author-abstracts
Authorization: Bearer {{token}}

### Get user's abstracts ###
GET http://localhost:8000/abstract/reviewer-abstracts
Authorization: Bearer {{reviewer_token}}



### Get abstract details ###
GET http://localhost:8000/abstract/abstract-details-author/35afacb2-c50f-4470-86f2-e29b99b7bb85
Authorization: Bearer {{token}}
