@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YjUzNGI3Mi0xMjdmLTQzMDgtOTI2NC04ODEzZGVkMDUzNTYiLCJpYXQiOjE3NzUzODc5NDksImV4cCI6MTc3NTk5Mjc0OX0.RIHaaj9COupqTXaXFgW5oH6w13LLKGGm3ICJdh4Q0rs
@refreshToken=


###Sign In ###
POST http://localhost:8000/auth/signin
Content-Type: application/json

{
 "email":"test@gmail.com",
 "password":"test123"
}


###Sign UP as Researcher ###
POST http://localhost:8000/auth/signup
Content-Type: application/json

{
    "name":"test",
    "email":"test@gmail.com",
    "phone":"01714906170",
    "password":"test123"

}

###Sign UP as  ADMIN ###
POST http://localhost:8000/auth/signup
Content-Type: application/json

{
    "name":"test",
    "email":"admin@gmail.com",
    "phone":"01743189984",
    "password":"test123",
    "role":"ADMIN"

}

###Sign UP as SUPER ADMIN ###
POST http://localhost:8000/auth/signup
Content-Type: application/json

{
    "name":"superadmin",
    "email":"su@gmail.com",
    "phone":"01712789976",
    "password":"test123",
    "role":"SUPERADMIN"

}



###profile ###
GET http://localhost:8000/auth/profile
Authorization: Bearer {{token}}


### Forget password ###
POST http://localhost:8000/auth/forgot-password
Content-Type: application/json

{
    "email":"diner.ragib@gmail.com"
}
